# Generated by Django 5.2 on 2025-06-24 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Operator'), (3, 'Owner'), (4, 'Teacher'), (5, 'Student')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, unique=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('city', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message="Enter a valid phone number (10-15 digits, optional '+' prefix).")])),
                ('number_of_students', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Number of students cannot be negative.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='school_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='main_app.school')),
            ],
            options={
                'unique_together': {('session_name', 'school')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main_app.school'),
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_guardian_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main_app.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('PG', 'PG'), ('Nursery', 'Nursery'), ('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=50)),
                ('roll_number', models.IntegerField()),
                ('section', models.CharField(choices=[('A_Red', 'A Red'), ('B_Blue', 'B Blue'), ('C_Green', 'C Green'), ('D_Yellow', 'D Yellow'), ('E_Purple', 'E Purple'), ('F_Orange', 'F Orange')], max_length=10)),
                ('admission_date', models.DateField()),
                ('class_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('book_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('uniform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('promotion_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('No', 'No')], default='No', max_length=10)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_behalf', models.CharField(blank=True, choices=[('owner', 'Owner'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('driver', 'Driver'), ('brothers_sisters', 'Brothers/Sisters')], max_length=20, null=True)),
                ('total_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('promoted', models.BooleanField(default=False)),
                ('failed_to_promote', models.BooleanField(default=False)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='main_app.academicsession')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='main_app.student')),
            ],
            options={
                'unique_together': {('roll_number', 'class_name', 'section', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('obtained_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], max_length=20)),
                ('percentage', models.FloatField(editable=False)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], editable=False, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main_app.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('PG', 'PG'), ('Nursery', 'Nursery'), ('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('books_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uniform_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paper_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.academicsession')),
            ],
            options={
                'unique_together': {('academic_session', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='main_app.studentadmission')),
            ],
            options={
                'unique_together': {('student_admission', 'month', 'year')},
            },
        ),
    ]
