# Generated by Django 5.2 on 2025-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='has_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='monthlyfee',
            index=models.Index(fields=['student_admission', 'month', 'year'], name='main_app_mo_student_968d06_idx'),
        ),
    ]
