# Generated by Django 5.2 on 2025-06-29 08:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_monthlyfee_has_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='practical',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='theory',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('MonthlyTest', 'MonthlyTest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='obtained_marks',
            field=models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main_app.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+92\\d{10}$|^03\\d{9}$', 'Enter a valid Pakistani phone number (e.g., +923xxxxxxxxx or 03xxxxxxxxx).')])),
                ('cnic', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Enter a valid CNIC (e.g., 12345-1234567-1).')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('class_name', models.CharField(choices=[('PG', 'PG'), ('Nursery', 'Nursery'), ('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=20)),
                ('section', models.CharField(choices=[('A_Red', 'A Red'), ('B_Blue', 'B Blue'), ('C_Green', 'C Green'), ('D_Yellow', 'D Yellow'), ('E_Purple', 'E Purple'), ('F_Orange', 'F Orange')], max_length=10)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_of_join', models.DateField()),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('children_in_school', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main_app.school')),
                ('subjects', models.ManyToManyField(blank=True, to='main_app.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'cnic', 'class_name', 'section')},
            },
        ),
    ]
