# Generated by Django 6.0.3 on 2026-06-08 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_teacher_cnic_unique_per_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance carried over from previous academic session', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='promoted_from',
            field=models.ForeignKey(blank=True, help_text='Reference to the StudentAdmission record from previous session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to', to='main_app.studentadmission'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Enter valid CNIC format.')]),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'cnic'], name='main_app_te_school__308d29_idx'),
        ),
    ]
