# Generated by Django 6.0.3 on 2026-06-10 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_studentadmission_previous_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final pending balance of this session (updated after every monthly payment)', max_digits=10),
        ),
    ]
