# Generated by Django 5.2 on 2025-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_studentresult_practical_studentresult_theory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student_admission', 'subject', 'exam_type')},
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Quiz', 'Quiz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='grade',
            field=models.CharField(editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='obtained_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='practical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='theory',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
    ]
