# Generated by Django 5.2 on 2025-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_studentresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
    ]
