# Generated by Django 6.0.3 on 2026-06-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_studentadmission_closing_balance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlyfee',
            name='main_app_mo_student_968d06_idx',
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='month_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='monthlyfee',
            index=models.Index(fields=['student_admission', 'year', 'month_number'], name='main_app_mo_student_ed5445_idx'),
        ),
    ]
