# Generated by Django 6.0.3 on 2026-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_monthlyfee_main_app_mo_student_968d06_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='close_time',
            field=models.TimeField(blank=True, help_text='School closing time (e.g. 14:00)', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='open_time',
            field=models.TimeField(blank=True, help_text='School opening time (e.g. 08:00)', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyfee',
            name='month_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
