# Generated by Django 6.0.3 on 2026-06-24 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_school_close_time_school_open_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_break', models.BooleanField(default=False, help_text='Mark as a break — no subject/teacher required.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='main_app.school')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ['order'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(choices=[('PG', 'PG'), ('Nursery', 'Nursery'), ('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], max_length=20)),
                ('section', models.CharField(choices=[('A_Red', 'A Red'), ('B_Blue', 'B Blue'), ('C_Green', 'C Green'), ('D_Yellow', 'D Yellow'), ('E_Purple', 'E Purple'), ('F_Orange', 'F Orange')], max_length=10)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='main_app.academicsession')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='main_app.period')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='main_app.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='main_app.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='main_app.teacher')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'indexes': [models.Index(fields=['school', 'academic_session', 'class_name', 'section'], name='main_app_ti_school__d46206_idx'), models.Index(fields=['teacher', 'academic_session'], name='main_app_ti_teacher_94260f_idx')],
                'unique_together': {('school', 'academic_session', 'class_name', 'section', 'period')},
            },
        ),
    ]
