# Generated by Django 6.0.3 on 2026-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_period_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assets',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='assets',
            name='file_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
