# Generated by Django 5.2 on 2025-07-15 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='class_name',
            field=models.CharField(choices=[('PG', 'PG'), ('Nursery', 'Nursery'), ('KG', 'KG'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10')], default='PG', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the syllabus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabi_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the syllabus content.'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='main_app.academicsession'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, help_text='Upload syllabus PDF if available.', null=True, upload_to='syllabus/'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='main_app.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('subject', 'class_name', 'academic_session')},
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['subject', 'class_name', 'academic_session'], name='main_app_sy_subject_2adbbb_idx'),
        ),
    ]
