# Generated by Django 6.0.3 on 2026-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_assets_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['school', 'payment_date'], name='main_app_ex_school__0f2aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='expenses',
            index=models.Index(fields=['school', 'expense_type'], name='main_app_ex_school__29a62e_idx'),
        ),
    ]
