# Generated by Django 5.2 on 2025-07-17 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_syllabus_class_name_syllabus_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Coordinator', 'Coordinator'), ('Librarian', 'Librarian'), ('Clerk', 'Clerk'), ('Accountant', 'Accountant'), ('Security Guard', 'Security Guard'), ('Janitor', 'Janitor'), ('Driver', 'Driver'), ('Other', 'Other')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_of_join', models.DateField()),
                ('cnic', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Enter a valid CNIC (e.g., 12345-1234567-1).')])),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+92\\d{10}$|^03\\d{9}$', 'Enter a valid Pakistani phone number (e.g., +923xxxxxxxxx or 03xxxxxxxxx).')])),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main_app.school')),
            ],
            options={
                'unique_together': {('school', 'cnic')},
            },
        ),
    ]
