# Generated by Django 6.0.3 on 2026-07-14 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_expenses_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='admission_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time discount applied to admission/promotion dues only', max_digits=10),
        ),
    ]
