# Generated by Django 5.2 on 2025-07-17 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchased_date', models.DateField()),
                ('file_number', models.CharField(max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('purchased_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='main_app.school')),
            ],
            options={
                'unique_together': {('school', 'file_number')},
            },
        ),
    ]
