# Generated by Django 5.2 on 2025-07-19 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily')], max_length=10)),
                ('expense_name', models.CharField(choices=[('Electricity Bill', 'Electricity Bill'), ('WiFi Bill', 'WiFi Bill'), ('Building Rent', 'Building Rent'), ('Carpenter', 'Carpenter'), ('Welder', 'Welder'), ('Event', 'Event'), ('First Aid', 'First Aid'), ('Sports', 'Sports'), ('Exam', 'Exam'), ('Other', 'Other'), ('Stationary', 'Stationary'), ('Food', 'Food')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_date', models.DateField()),
                ('payment_by', models.CharField(max_length=100)),
                ('file_number', models.CharField(blank=True, max_length=50, null=True)),
                ('month_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main_app.school')),
            ],
        ),
    ]
