# Generated by Django 5.2 on 2025-07-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='month_name',
            new_name='period',
        ),
    ]
