# Generated by Django 5.2 on 2025-07-19 07:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_month_name_expenses_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_name',
            field=models.CharField(choices=[('Electricity Bill', 'Electricity Bill'), ('WiFi Bill', 'WiFi Bill'), ('Building Rent', 'Building Rent'), ('Carpenter', 'Carpenter'), ('Transport', 'Transport'), ('Welder', 'Welder'), ('Event', 'Event'), ('First Aid', 'First Aid'), ('Sports', 'Sports'), ('Exam', 'Exam'), ('Other', 'Other'), ('Stationary', 'Stationary'), ('Food', 'Food')], max_length=50),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_cnic', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d{1}$', 'CNIC must be in the format 12345-1234567-1')])),
                ('address', models.TextField()),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('number_of_students', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Contact must be a valid phone number')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='main_app.school')),
            ],
            options={
                'unique_together': {('school', 'vehicle_number')},
            },
        ),
    ]
