# Generated by Django 5.2 on 2025-07-19 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_expenses_expense_name_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Exam', 'Exam'), ('TPM', 'TPM'), ('Teacher Meeting', 'Teacher Meeting'), ('Result', 'Result'), ('Celebration', 'Celebration'), ('Tour', 'Tour'), ('Other', 'Other')], max_length=20)),
                ('event_for', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Teacher', 'Teacher')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('announcement_date', models.DateField(default=django.utils.timezone.now)),
                ('arranged_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.school')),
            ],
        ),
    ]
