# Generated by Django 6.0.3 on 2026-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_syllabus_main_app_sy_subject_2adbbb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_name',
            field=models.CharField(choices=[('Electricity Bill', 'Electricity Bill'), ('WiFi Bill', 'WiFi Bill'), ('Building Rent', 'Building Rent'), ('Carpenter', 'Carpenter'), ('Transport', 'Transport'), ('Welder', 'Welder'), ('Event', 'Event'), ('Electrecian', 'Elecrecian'), ('Maintain', 'Maintain'), ('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Tools', 'Tools'), ('First Aid', 'First Aid'), ('Sports', 'Sports'), ('Exam', 'Exam'), ('Other', 'Other'), ('Stationary', 'Stationary'), ('Food', 'Food')], max_length=50),
        ),
    ]
