# Generated by Django 6.0.3 on 2026-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_studentresult_grade_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'is_active'], name='main_app_ac_school__5bab71_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['school', 'start_date', 'end_date'], name='main_app_ac_school__36f0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='academicsession',
            index=models.Index(fields=['is_active'], name='main_app_ac_is_acti_9a6c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfee',
            index=models.Index(fields=['student_admission', 'year'], name='main_app_mo_student_93795e_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfee',
            index=models.Index(fields=['has_payment'], name='main_app_mo_has_pay_21e5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfee',
            index=models.Index(fields=['student_admission', 'payment_date'], name='main_app_mo_student_60128c_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='main_app_sc_is_acti_148b88_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['city'], name='main_app_sc_city_12eece_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'student_id'], name='main_app_st_school__34003e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school'], name='main_app_st_school__a6500d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='main_app_st_first_n_a2a349_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['academic_session', 'class_name', 'section'], name='main_app_st_academi_2a8166_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['student', 'academic_session'], name='main_app_st_student_667e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['roll_number', 'class_name', 'section', 'academic_session'], name='main_app_st_roll_nu_fe23ad_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['promoted', 'failed_to_promote'], name='main_app_st_promote_8bd509_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['status'], name='main_app_st_status_a685b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmission',
            index=models.Index(fields=['academic_session', 'student'], name='main_app_st_academi_54e363_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['student_admission', 'subject', 'exam_type'], name='main_app_st_student_185ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['student_admission'], name='main_app_st_student_7c7aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentresult',
            index=models.Index(fields=['exam_type'], name='main_app_st_exam_ty_eade39_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['school', 'class_name', 'academic_session'], name='main_app_sy_school__8d4eae_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['subject', 'class_name'], name='main_app_sy_subject_f75feb_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'class_name', 'section'], name='main_app_te_school__e80a11_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school'], name='main_app_te_school__c62c7d_idx'),
        ),
    ]
