# Generated by Django 6.0.3 on 2026-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_academicsession_main_app_ac_school__5bab71_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('Exam', 'Exam'), ('TPM', 'TPM'), ('Teacher Meeting', 'Teacher Meeting'), ('Result', 'Result'), ('Celebration', 'Celebration'), ('Tour', 'Tour'), ('Other', 'Other'), ('Vocation', 'Vocation')], max_length=20),
        ),
    ]
